frozenInstalls: true

initLicense: MIT

initScope: 'meatwallace'

initVersion: 1.0.0-development

lastUpdateCheck: 1560910052890

npmPublishAccess: public

npmPublishRegistry: 'https://registry.yarnpkg.com/'

plugins:
  - .yarn/plugins/@berry/plugin-typescript.js
